name: Draw ZMK keymaps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  draw:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the token has write permissions

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Draw keymaps
      run: |
        keymap "${config_arg[@]}" draw "keymap-drawer/$keyboard.yaml" $draw_args >"keymap-drawer/$keyboard.svg" \
        || {
          keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args >"keymap-drawer/$keyboard.yaml"
          echo "ERROR: parsing or drawing failed for $keyboard!"
          error_occurred=1
        }
        DRAWINGS+=("keymap-drawer/$keyboard.yaml" "keymap-drawer/$keyboard.svg")
      shell: bash

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update keymap drawings"
        branch: main
        commit_options: --no-verify
        file_pattern: keymap-drawer/*
